spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:

        - id: ms-copart-api-docs
          uri: http://localhost:8083
          predicates:
            - Path=/service-copart
          filters:
            - RewritePath=/service-copart, /v3/api-docs
        - id: swagger
          uri: http://localhost:8080
          predicates:
            - Path=/swagger-ui
          filters:
            - RewritePath=/swagger-ui, /swagger-ui/index.html

        - id: ms-auth-api-docs
          uri: http://localhost:8082
          predicates:
            - Path=/service-auth
          filters:
            - RewritePath=/service-auth, /v3/api-docs

        - id: ms-file-api-docs
          uri: http://localhost:8085
          predicates:
            - Path=/service-file
          filters:
            - RewritePath=/service-file, /v3/api-docs


        - id: ms-copart
          uri: http://localhost:8083
          predicates:
            - Path=/copart/**
          filters:
            - RewritePath=/copart/(?<segment>.*), /api/v1/${segment}

        - id: ms-auth
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /api/v1/${segment}

        - id: ms-file
          uri: http://localhost:8085
          predicates:
            - Path=/file/**
          filters:
            - RewritePath=/file/(?<segment>.*), /api/v1/${segment}


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      -   name: gateway-service
          url: /v3/api-docs
    disable-swagger-default-url: false
